import type { Metadata } from "next";
import "./globals.css";
import { Nunito, Syne } from "next/font/google";
import FinalClerkConvexProvider from "@/components/final-clerk-convex-provider";

const nunito = Nunito({
  subsets: ["latin"],
  variable: "--font-nunito",
});

const syne = Syne({
  subsets: ["latin"],
  variable: "--font-syne",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <FinalClerkConvexProvider>
      <html lang="en">
        <body className={`${nunito.className} ${syne.variable} antialiased`}>
          {children}
        </body>
      </html>
    </FinalClerkConvexProvider>
  );
}
